name: mega
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - alembic
  - babel
  - blinker
  - ca-certificates
  - click
  - dataclasses
  - dnspython
  - ecdsa
  - email-validator
  - flask
  - flask-babel
  - flask-login
  - flask-sqlalchemy
  - flask-wtf
  - gmp
  - greenlet
  - idna
  - importlib-metadata
  - importlib_resources
  - itsdangerous
  - jinja2
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libgomp
  - libstdcxx-ng
  - mako
  - markupsafe
  - ncurses
  - openssl
  - pycryptodome
  - pyjwt
  - python
  - pip==21.3
  - pip:
    - dominate
    - flask-bootstrap
    - flask-mail
    - flask-migrate
    - flask-moment
    - python_abi
    - visitor
  - pytz
  - readline
  - setuptools
  - six
  - sqlalchemy
  - sqlite
  - tk
  - tzdata
  - werkzeug
  - wheel
  - wtforms
  - xz
  - zipp
  - zlib
