name: at-portfolio-app
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - alembic
  - babel
  - blinker
  - ca-certificates
  - click
  - dataclasses
  - dnspython
  - dominate
  - ecdsa
  - email-validator
  - flask
  - flask-babel
  - flask-bootstrap
  - flask-login
  - flask-mail
  - flask-migrate
  - flask-moment
  - flask-sqlalchemy
  - flask-wtf
  - gmp
  - greenlet
  - idna
  - importlib-metadata
  - importlib_resources
  - itsdangerous
  - jinja2
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libgomp
  - libstdcxx-ng
  - libzlib
  - mako
  - markupsafe
  - ncurses
  - openssl
  - pip
  - pycryptodome
  - pyjwt
  - python
  - python_abi
  - pytz
  - readline
  - setuptools
  - six
  - sqlalchemy
  - sqlite
  - tk
  - tzdata
  - visitor
  - werkzeug
  - wheel
  - wtforms
  - xz
  - zipp
  - zlib
