"""Reset db

Revision ID: bc5221749cb0
Revises: 
Create Date: 2021-10-28 16:12:25.892992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc5221749cb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_block', sa.String(), nullable=False),
    sa.Column('iframes', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eda')
    # ### end Alembic commands ###
